# Generated by Django 4.2.30 on 2026-08-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('UPI', 'UPI Instant Pay (Google Pay, PhonePe, Paytm)'), ('CARD', 'Credit / Debit Card (Visa, Mastercard, RuPay)'), ('NETBANKING', 'Net Banking (All Indian Banks)'), ('COD', 'Cash on Delivery'), ('ONLINE_TEST', 'Online Payment (Razorpay Simulated Gateway)')], default='ONLINE_TEST', max_length=25),
        ),
    ]
